#!/bin/bash

#==============================================================================
#         FILE: vulpes
#        USAGE: see usage function
#  DESCRIPTION: script for running, developing, and creating vulpes apps
# REQUIREMENTS: node, npm, nodemon
#==============================================================================

VULPES_DIR=`dirname $(readlink -f $0)`

#=== FUNCTION =================================================================
#        NAME: usage
# DESCRIPTION: outputs usage text
#==============================================================================
usage() {
    echo "Usage: vulpes [command] [options]"
    echo
    echo "Commands:"
    echo
    echo "  start           # start a vulpes app"
    echo "  watch           # start a vulpes app and restart on updates"
    echo "  create          # create a new vulpes app"
    echo
    echo "Options:"
    echo
    echo "  -h, --help      # view this help text"
}

#=== FUNCTION =================================================================
#        NAME: watch_app
# DESCRIPTION: starts nodemon and makes it watch the app and config dirs
#==============================================================================
watch_app() {
    NODE_ENV=development \
    nodemon --exec "vulpes start $@" \
        -w app -w config
}

#=== FUNCTION =================================================================
#        NAME: start_app
# DESCRIPTION: starts the vulpes server
#==============================================================================
start_app() {
    [ -z "$DEBUG" ] && DEBUG=*
    DEBUG=$DEBUG \
    NODE_PATH=`pwd`/node_modules/ \
    node `pwd`/node_modules/vulpes/src/server $@
}

#=== FUNCTION =================================================================
#        NAME: create_app
# DESCRIPTION: copies the samples/base directory as a new, blank, vulpes
#              application and installs all dependencies
# PARAMETER 1: app - application name. must be a single word (for npm)
#==============================================================================
create_app() {
    local app=$1

    if [ -z "$app" ]; then
        while true;
        do
            echo -n "name: "
            read app
            [ ! -z "$app" ] && break
        done
    fi

    echo "creating $app app"
    cp -r $VULPES_DIR/samples/basic/ $app
    cd $app
    sed -i "s/%APP%/$app/" bower.json package.json
    make
}

case "$1" in
    watch) shift; watch_app $* ;;
    start) shift; start_app $* ;;
    create) create_app $2 ;;
    --help|-h) usage ;;
    *) usage; exit 1 ;;
esac
