#!/bin/bash

#==============================================================================
#         FILE: vulpes
#        USAGE: see usage function
#  DESCRIPTION: script for running, developing, and creating vulpes projects
# REQUIREMENTS: node, npm, nodemon
#==============================================================================

[ -z "$VULPES_HOME" ] && VULPES_HOME=$(dirname "$(readlink -f "$0")")

#=== FUNCTION =================================================================
#        NAME: usage
# DESCRIPTION: outputs usage text
#==============================================================================
usage() {
    echo "Usage: vulpes [command] [options]"
    echo
    echo "Commands:"
    echo
    echo "  start           # start a vulpes project"
    echo "  watch           # start a vulpes project and restart on updates"
    echo "  create          # create a new vulpes project"
    echo
    echo "Options:"
    echo
    echo "  -h, --help      # view this help text"
}

#=== FUNCTION =================================================================
#        NAME: watch
# DESCRIPTION: starts nodemon and makes it watch the project and config dirs
#==============================================================================
watch() {
    NODE_ENV=development \
    nodemon --exec "vulpes start $@" \
        -w app -w config
}

#=== FUNCTION =================================================================
#        NAME: start
# DESCRIPTION: starts the vulpes server
#==============================================================================
start() {
    [ -z "$DEBUG" ] && DEBUG='*'
    DEBUG=$DEBUG \
    NODE_PATH="$(pwd)/node_modules/" \
    node "$(pwd)/node_modules/vulpes/src/server" "$@"
}

#=== FUNCTION =================================================================
#        NAME: create
# DESCRIPTION: copies the samples/base directory as a new, blank, vulpes
#              project and installs all dependencies
# PARAMETER 1: project - project name. must be a single word (for npm)
#==============================================================================
create() {
    local project=$1

    if [ -z "$project" ]; then
        while true;
        do
            echo -n "name: "
            read project
            [ ! -z "$project" ] && break
        done
    fi

    echo "creating $project project"
    cp -r "$VULPES_HOME/samples/basic/" "$project"
    cd "$project"
    sed -i "s/%APP%/$project/" bower.json package.json
    make
}

if [ -z "$1" ]; then
    start
else
    case "$1" in
        watch) shift; watch "$@" ;;
        start) shift; start "$@" ;;
        create) create "$2" ;;
        --help|-h) usage ;;
        *) usage; exit 1 ;;
    esac
fi
