#!/bin/bash

VULPES_DIR=`dirname $(readlink -f $0)`

usage() {
    echo "Usage: vulpes [command] [options]"
    echo
    echo "Commands:"
    echo
    echo "  start           # start a vulpes app"
    echo "  watch           # start a vulpes app and restart on updates"
    echo "  create          # create a new vulpes app"
    echo
    echo "Options:"
    echo
    echo "  -h, --help      # view this help text"
}

watch_app() {
    NODE_ENV=development \
    nodemon --exec "vulpes start $@" \
        -w app -w config
}

start_app() {
    DEBUG=* \
    NODE_PATH=`pwd`/node_modules/ \
    node `pwd`/node_modules/vulpes/src/server $@
}

create_app() {
    local app=$1

    if [ -z "$app" ]; then
        while true;
        do
            echo -n "name: "
            read app
            [ ! -z "$app" ] && break
        done
    fi

    echo "creating $app app"
    mkdir $app
    cd $app

    cp -r $VULPES_DIR/sample_application/* ./
    sed -i "s/%APP%/$app/" bower.json package.json assets/views/index.html
}

case "$1" in
    watch) shift; watch_app $* ;;
    start) shift; start_app $* ;;
    create) create_app $2 ;;
    --help|-h) usage ;;
    *) usage; exit 1 ;;
esac
