aliases:
  ci:
    - 'clean'
    - 'prepare'
    - 'quality'
    - 'test'
  default:
    - 'ci'
  test:
    - 'test:unit'
  test:unit:
    - 'exec:mocha'
  quality:
    - 'prepare'
    - 'complexity:all'
    - 'htmlhint:all'
    - 'jshint:all'
    - 'jshint:report'
  documentation:
    - 'yuidoc:all'
    - 'apidoc:all'

files:
  js:
    dir: lib
    all: lib/**/**.js
