imports: [ ./vendor/minond/scaffold/config/defbuild.yml ]

aliases:
  test:
    - 'test:unit'
  test:unit:
    - 'test:unit:js'
  quality:
  - 'prepare'
  - 'complexity:all'
  - 'htmlhint:all'
  - 'jshint:all'
  - 'jshint:report'
