aliases:
  test:
    - 'test:unit'
  test:unit:
    - 'exec:mocha'
  quality:
  - 'prepare'
  - 'complexity:all'
  - 'htmlhint:all'
  - 'jshint:all'
  - 'jshint:report'

files:
  js:
    dir: lib
    all: lib/**.js
