#!/usr/bin/env node
// vi:syntax=javascript

var color = require('cli-color');

console.log(color.xterm(232)('                        '));
console.log(color.xterm(254)('     /\\                '));
console.log(color.xterm(222)('    (~(                 '));
console.log(color.xterm(222)('     ) )     /\\_/\\    '));
console.log(color.xterm(222)('    ( _-----_(- -)      '));
console.log(color.xterm(222)('      (       \\ /      '));
console.log(color.xterm(222)('      /|/--\\|\\ V      '));
console.log(color.xterm(244)('      " "   " "         '));
console.log(color.xterm(232)('                        '));

process.env.NODE_PATH = process.cwd() + '/node_modules/';
require('./server');
